name: CI Deploy DEV

on:
  push:
    branches: [develop]
  workflow_dispatch:
    int_tests:
      description: Run integration tests
      required: false
      default: false
      type: boolean

jobs:
  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/wf-deploy.yml
    with:
      environment_name: development
    secrets: inherit

  integration-tests:
    if: ${{ github.actor != 'dependabot[bot]' && inputs.int_tests }}
    uses: ./.github/workflows/wf-test.yml
    needs: deploy
    with:
      environment_name: development