name: ~Deploy

on:
  workflow_call:
    inputs:
      environment_name:
        description: Environment
        required: false
        default: development
        type: string
  workflow_dispatch:
    inputs:
      environment_name:
        description: Environment
        required: false
        default: development
        type: choice
        options:
          - development
          - staging
          - prod

jobs:
  deploy:
    name: Deploy APIs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install-Test
        run: |
          npm ci

      # - name: Install SAM
      #   uses: aws-actions/setup-sam@v2

      - name: Build
        run: npm run build

      # - name: Deploy Stack
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      #     AWS_ROLE: CIDeployAccess
      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_NONPROD }} # PROD not working!
      #     AWS_BUCKET_NAME: ds-customer-api-${{ inputs.environment_name }}
      #     AWSENV: ${{ inputs.environment_name }}
      #   run: |
      #     # .deploy/aws-sam-validate.sh samconfig-staging.toml # ERROR: 'AuthApi', "Unable to add Cors configuration because 'DefinitionBody' does not contain a valid Swagger definition."
      #     .deploy/aws-sam-deploy.sh samconfig-${{ inputs.environment_name }}.toml